// Code generated by mockery v2.26.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IServiceSystem is an autogenerated mock type for the IServiceSystem type
type IServiceSystem struct {
	mock.Mock
}

// GetSwagger provides a mock function with given fields:
func (_m *IServiceSystem) GetSwagger() ([]byte, error) {
	ret := _m.Called()

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIServiceSystem interface {
	mock.TestingT
	Cleanup(func())
}

// NewIServiceSystem creates a new instance of IServiceSystem. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIServiceSystem(t mockConstructorTestingTNewIServiceSystem) *IServiceSystem {
	mock := &IServiceSystem{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
