version: '3.0'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
#  caddy:
#    image: caddy:latest
#    volumes:
#      - './caddy/Caddyfile:/etc/caddy/Caddyfile:ro'
#      - './caddy/data:/data'
#      - './caddy/config:/config'
#    ports:
#      - 443:443
  db:
    image: postgres:latest
    volumes:
      - '/tmp/db_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=mmr_boost
      - POSTGRES_USER=mmr_boost
      - POSTGRES_DB=db
    ports:
      - 5432:5432
