version: '3.0'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
  swagger:
    image: swaggerapi/swagger-ui
    logging:
      driver: none
    ports:
      - 8081:8080
    environment:
      URLS: "[ { url: 'http://localhost:8080/api/v1/system/swagger' } ]"
