version: '3.0'

services:
  app:
    image: golang:latest
    volumes:
      - '.:/home/app:ro'
    env_file:
      - .env
    working_dir: '/home/app'
    ports:
      - 80:8080
    command: sh -c "./server"
  db:
    image: postgres:latest
    volumes:
      - './db_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=mmr_boost
      - POSTGRES_USER=mmr_boost
      - POSTGRES_DB=db
