version: '3.0'

services:
  db:
    image: postgres:latest
    volumes:
      - '/tmp/db_data:/var/lib/postgresql/data'
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      - POSTGRES_PASSWORD=mmr_boost
      - POSTGRES_USER=mmr_boost
      - POSTGRES_DB=db
